<?php

namespace Database\Seeders;

use App\Models\Divisi;
use App\Models\Kegiatan;
use Illuminate\Database\Seeder;

class KegiatanSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $divisi = Divisi::all()->pluck('id')->toArray();
        $kegiatan = [
            [
                'nama_kegiatan' => 'Penyusunan SOP Organisasi',
                'deskripsi_kegiatan' => "Gambaran Umum:\nMelaksanakan pertemuan rutin untuk menjaga koordinasi antar fungsionaris dengan memaparkan progress dan kendala yang dialami sebagai bentuk integrasi lembaga.\n\nTujuan:\n- Terpenuhi target-target kegiatan\n- Ruang diskusi dari setiap permasalahan\n\nManfaat:\n- Terintegrasinya peran dan fungsi tiap divisi\n- Meningkatkan hubungan komunikasi antar fungsionaris\n\nSasaran:\n- Fungsionaris KMI/KKMI\n- DPO & Alumni KMI\n- Eksternal Lembaga & Stakeholder\n\nTanggal:\n2023-05-01\n\nLokasi:\nGedung KMI\n\nParameter Keberhasilan:\n- Terlaksananya kegiatan sesuai rencana",
                'divisi_id' => $divisi[0],
                'status' => 'aktif',
                'total_biaya' => 0,
                'target_biaya' => 0,
            ],
            [
                'nama_kegiatan' => 'Rapat Besar Pengurus (RBP KMI) 2023',
                'deskripsi_kegiatan' => "Gambaran Umum:\nPertemuan rutin untuk menjaga koordinasi antar fungsionaris, memaparkan progress dan kendala sebagai bentuk integrasi lembaga.\n\nTujuan:\n- Terpenuhi target kegiatan\n- Diskusi permasalahan\n\nManfaat:\n- Terintegrasinya peran dan fungsi tiap divisi\n- Meningkatkan komunikasi\n\nSasaran:\n- Fungsionaris KMI/KKMI\n- DPO & Alumni KMI\n- Eksternal Lembaga & Stakeholder\n\nTanggal:\n2023-06-25\n\nLokasi:\nGoogle Meet\n\nParameter Keberhasilan:\n- Terselenggaranya rapat besar dan tercapainya keputusan bersama",
                'divisi_id' => $divisi[0],
                'status' => 'aktif',
                'total_biaya' => 0,
                'target_biaya' => 0,
            ],
            [
                'nama_kegiatan' => 'Rapat Triwulan 1 & 2',
                'deskripsi_kegiatan' => "Gambaran Umum:\nRapat Evaluasi Capaian Kinerja dan Realisasi Anggaran Lembaga Dakwah Kampus Se-UPN Periode 2023 (KKMI Yang Memperoleh Pendanaan).\n\nTujuan:\n- Monitoring realisasi anggaran\n- Evaluasi permasalahan pelaksanaan target kinerja\n\nManfaat:\n- Integrasi kinerja Lembaga Dakwah\n- Inventarisasi permasalahan\n\nSasaran:\n- Fungsionaris KMI-KKMI\n- Mahasiswa Muslim UPN\n- Alumni\n\nTanggal:\n2023-07-30\n\nLokasi:\n-\n\nParameter Keberhasilan:\n- Terevaluasinya capaian kinerja dan realisasi anggaran",
                'divisi_id' => $divisi[0],
                'status' => 'aktif',
                'total_biaya' => 0,
                'target_biaya' => 0,
            ],
            [
                'nama_kegiatan' => 'Musyawarah Kerja',
                'deskripsi_kegiatan' => "Gambaran Umum:\nProses rembukan untuk menentukan dan merumuskan agenda serta program kerja selama satu periode kepengurusan.\n\nTujuan:\n- Wadah kewenangan tertinggi menentukan langkah organisasi\n\nManfaat:\n- Tersusunnya program\n- Wadah diskusi\n- Integrasi pemikiran\n\nSasaran:\n- Fungsionaris KMI-KKMI\n- Mahasiswa Muslim UPN\n- Alumni\n\nTanggal:\n2023-05-21\n\nLokasi:\nRuang Seminar FEB\n\nParameter Keberhasilan:\n- Tersusunnya program kerja periode berjalan",
                'divisi_id' => $divisi[0],
                'status' => 'aktif',
                'total_biaya' => 0,
                'target_biaya' => 500000,
            ],
            [
                'nama_kegiatan' => 'Musyawarah Besar',
                'deskripsi_kegiatan' => "Gambaran Umum:\nEvaluasi kegiatan organisasi sebelumnya dan momentum pembentukan kepengurusan baru.\n\nTujuan:\n- Menentukan Ketua Umum\n- Menetapkan AD ART dan GBHD KMI\n\nManfaat:\n- Mahasiswa kritis\n- Memperoleh pemimpin baru\n\nSasaran:\n- Fungsionaris KMI-KKMI\n- Mahasiswa Muslim UPN\n- Alumni\n\nTanggal:\n2023-11-22\n\nLokasi:\nMasjid NTQ, Ruang Seminar FISIP dan Ruang Seminar FEB\n\nParameter Keberhasilan:\n- Terlaksananya musyawarah besar dan terpilihnya ketua umum baru",
                'divisi_id' => $divisi[0],
                'status' => 'aktif',
                'total_biaya' => 0,
                'target_biaya' => 2000000,
            ],
            [
                'nama_kegiatan' => 'Kalender KMI/KKMI',
                'deskripsi_kegiatan' => "Gambaran Umum:\nTabel jadwal penganggendaan program kerja pengurus selama masa kepengurusan.\n\nTujuan:\n- Integrasi jadwal tiap divisi/lembaga\n- Menghindari bentrok jadwal\n\nManfaat:\n- Timeline syiar terlaraskan\n\nSasaran:\n- Fungsionaris KMI-KKMI\n\nTanggal:\n2023-05-21\n\nLokasi:\nRuang Seminar FEB\n\nParameter Keberhasilan:\n- Tersusunnya kalender kegiatan KMI/KKMI",
                'divisi_id' => $divisi[0],
                'status' => 'aktif',
                'total_biaya' => 0,
                'target_biaya' => 0,
            ],
            [
                'nama_kegiatan' => 'Achievement KMI/KKMI',
                'deskripsi_kegiatan' => "Gambaran Umum:\nPemberian penghargaan bagi fungsionaris berprestasi dan aktif sebagai motivasi dan semangat kader.\n\nTujuan:\n- Membangkitkan semangat beramal dan berkontribusi\n\nManfaat:\n- Menjaga loyalitas\n- Meningkatkan rasa kepemilikan\n\nSasaran:\n- Fungsionaris KMI-KKMI\n\nTanggal:\n2023-12-15\n\nLokasi:\nMedia Instagram dan Menyesuaikan\n\nParameter Keberhasilan:\n- Terlaksananya pemberian penghargaan kepada fungsionaris",
                'divisi_id' => $divisi[0],
                'status' => 'aktif',
                'total_biaya' => 0,
                'target_biaya' => 500000,
            ],
            [
                'nama_kegiatan' => 'Penyusunan SOP Administrasi KMI/KKMI',
                'deskripsi_kegiatan' => "Gambaran Umum:\nProsedur standar umum kegiatan lembaga.\n\nTujuan:\n- Identifikasi, susun, dokumentasi, evaluasi SOP sesuai tugas fungsionaris\n\nManfaat:\n- Membantu penelusuran kesalahan prosedural\n- Informasi standar pelayanan\n\nSasaran:\n- Fungsionaris KMI-KKMI\n- Lembaga Eksternal\n\nTanggal:\n2023-05-21\n\nLokasi:\nGoogle Drive\n\nParameter Keberhasilan:\n- Tersusunnya SOP administrasi KMI/KKMI",
                'divisi_id' => $divisi[0],
                'status' => 'aktif',
                'total_biaya' => 0,
                'target_biaya' => 0,
            ],
            [
                'nama_kegiatan' => 'Inventarisasi',
                'deskripsi_kegiatan' => "Gambaran Umum:\nMencatat dan menyusun daftar inventaris barang milik lembaga secara teratur.\n\nTujuan:\n- Kelancaran administrasi\n- Pengawasan aset\n\nManfaat:\n- Peralatan tidak mudah hilang\n- Bukti tertulis pengelolaan barang\n\nSasaran:\n- Peralatan dan perlengkapan KMI\n\nTanggal:\n2023-05-14\n\nLokasi:\nSekretariat KMI\n\nParameter Keberhasilan:\n- Tersusunnya daftar inventaris lembaga",
                'divisi_id' => $divisi[0],
                'status' => 'aktif',
                'total_biaya' => 0,
                'target_biaya' => 0,
            ],
            [
                'nama_kegiatan' => 'Pembuatan Jadwal Piket Sekretariat',
                'deskripsi_kegiatan' => "Gambaran Umum:\nMenjaga stand pelayanan ummat dan kebersihan ruangan sekretariat.\n\nTujuan:\n- Membantu pelayanan ummat\n- Menjaga kebersihan sekretariat\n\nManfaat:\n- Ruang sekretariat terkelola baik\n- Pelayanan maksimal\n\nSasaran:\n- Fungsionaris KMI\n\nTanggal:\n2023-05-01\n\nLokasi:\nSekretariat KMI\n\nParameter Keberhasilan:\n- Terlaksananya jadwal piket dan ruang sekretariat terjaga",
                'divisi_id' => $divisi[0],
                'status' => 'aktif',
                'total_biaya' => 0,
                'target_biaya' => 0,
            ],
            [
                'nama_kegiatan' => 'Pendataan Kader KMI 2023',
                'deskripsi_kegiatan' => "Gambaran Umum:\nPengumpulan data fungsionaris sebagai informasi pendukung administrasi organisasi.\n\nTujuan:\n- Memenuhi kebutuhan fungsionaris\n- Sumber informasi organisasi\n\nManfaat:\n- Pengelolaan fungsionaris\n- Kemudahan pencarian data kader\n\nSasaran:\n- Fungsionaris KMI\n\nTanggal:\n2023-05-01\n\nLokasi:\nGoogle Form & WhatsApp Group\n\nParameter Keberhasilan:\n- Tersedianya data kader KMI secara lengkap",
                'divisi_id' => $divisi[0],
                'status' => 'aktif',
                'total_biaya' => 0,
                'target_biaya' => 0,
            ],
            [
                'nama_kegiatan' => 'Penyusunan SOP Bendahara',
                'deskripsi_kegiatan' => "Gambaran Umum:\nSOP Bendahara: SOP Pembagian Hasil Proker, Rancangan Anggaran, Laporan Keuangan, Peminjaman Dana, Pengeluaran Kas, SPJ Keuangan.\n\nTujuan:\n- Prosedur keuangan jelas\n- Akuntabilitas dana\n\nManfaat:\n- Transparansi pelaporan\n- Kemudahan pertanggungjawaban\n\nSasaran:\n- Fungsionaris KMI/KKMI\n\nTanggal:\n2023-01-01\n\nLokasi:\nGoogle Drive\n\nParameter Keberhasilan:\n- Tersusunnya SOP bendahara dan diterapkan dalam pengelolaan keuangan",
                'divisi_id' => $divisi[0],
                'status' => 'aktif',
                'total_biaya' => 0,
                'target_biaya' => 0,
            ],
            [
                'nama_kegiatan' => 'Pengadaan Kas & Iuran Anggota',
                'deskripsi_kegiatan' => "Gambaran Umum:\nKontribusi anggota terhadap organisasi (KMI), pelaksanaan selama 7 bulan dalam 1 periode kabinet.\n\nTujuan:\n- Mendukung operasional organisasi dan proker\n\nManfaat:\n- Mempermudah pendanaan sementara\n\nSasaran:\n- Fungsionaris KMI\n\nTanggal:\n2023-06-01\n\nLokasi:\n-\n\nParameter Keberhasilan:\n- Terkumpulnya kas dan iuran anggota sesuai target",
                'divisi_id' => $divisi[0],
                'status' => 'aktif',
                'total_biaya' => 0,
                'target_biaya' => 0,
            ],
            [
                'nama_kegiatan' => 'Arsip RAB Proposal',
                'deskripsi_kegiatan' => "Gambaran Umum:\nPengarsipan data RAB sebagai referensi dan tolak ukur anggaran kegiatan.\n\nTujuan:\n- Penyesuaian anggaran dengan kebutuhan\n- Kemudahan penyusunan RAB\n\nManfaat:\n- Memudahkan penyusunan RAB program kerja\n\nSasaran:\n- Proposal Program Kerja\n\nTanggal:\n2023-06-01\n\nLokasi:\nGoogle Drive\n\nParameter Keberhasilan:\n- Tersedianya arsip RAB proposal yang terdokumentasi",
                'divisi_id' => $divisi[0],
                'status' => 'aktif',
                'total_biaya' => 0,
                'target_biaya' => 0,
            ],
            //Divisi BK KKMI
            [
                'nama_kegiatan' => 'Kanal Informasi KKMI',
                'divisi_id' => $divisi[1],
                'deskripsi_kegiatan' => "Gambaran Umum:\nMenyampaikan segala informasi yang diperuntukkan kepada KKMI baik secara formal maupun non formal melalui luring ataupun daring.\n\nTujuan:\n- Tersampaikannya berbagai informasi yang diperuntukkan kepada KKMI\n\nManfaat:\n- KKMI mendapatkan informasi dengan baik dan jelas\n\nSasaran:\n- Seluruh KKMI di lingkungan UPN Veteran Yogyakarta\n\nTanggal:\n2023-05-01\n\nLokasi:\nMenyesuaikan\n\nParameter Keberhasilan:\n- Informasi tersampaikan ke seluruh KKMI",
                'status' => 'aktif',
                'total_biaya' => 0,
                'target_biaya' => 0,
            ],
            [
                'nama_kegiatan' => 'Safari KKMI',
                'divisi_id' => $divisi[1],
                'deskripsi_kegiatan' => "Gambaran Umum:\nMelakukan safari atau anjangsana kepada KKMI di lingkungan UPN Veteran Yogyakarta. Kegiatan diisi dengan penyampaian kondisi KKMI, diskusi sharing, dan dengar pendapat dari KKMI serta pemberian informasi dari KMI.\n\nTujuan:\n- Menjalin silaturahmi\n- Mendapat update informasi kondisi KKMI\n- Mengevaluasi kinerja KMI\n\nManfaat:\n- Terjalin silaturahmi\n- Ter-updatenya informasi kondisi KKMI\n- Terevaluasinya kinerja KKMI-KMI\n\nSasaran:\n- Anggota/pengurus aktif dari KMI maupun KKMI di lingkungan UPN Veteran Yogyakarta\n\nTanggal:\n2023-05-25\n\nLokasi:\nMenyesuaikan\n\nParameter Keberhasilan:\n- Terselenggaranya safari dan laporan hasil kunjungan",
                'status' => 'aktif',
                'total_biaya' => 0,
                'target_biaya' => 300000,
            ],
            [
                'nama_kegiatan' => 'Forum Ketua KKMI',
                'divisi_id' => $divisi[1],
                'deskripsi_kegiatan' => "Gambaran Umum:\nPertemuan seluruh ketua KKMI dan KMI untuk bertukar pikiran, menyatukan tujuan, diskusi antar ketua terkait persoalan di KMI maupun KKMI.\n\nTujuan:\n- Menyelesaikan persoalan internal dan eksternal di KMI maupun KKMI\n- Menjalin silaturahmi\n\nManfaat:\n- Tersolusikan persoalan internal dan eksternal di KMI maupun KKMI\n- Terjalin silaturahmi\n\nSasaran:\n- Seluruh ketua KKMI dan KMI periode aktif\n\nTanggal:\n2023-06-26\n\nLokasi:\nMenyesuaikan\n\nParameter Keberhasilan:\n- Terselenggaranya forum dan solusi atas permasalahan",
                'status' => 'aktif',
                'total_biaya' => 0,
                'target_biaya' => 300000,
            ],
            [
                'nama_kegiatan' => 'Silaturahmi Akbar Lembaga Dakwah',
                'divisi_id' => $divisi[1],
                'deskripsi_kegiatan' => "Gambaran Umum:\nDiadakannya forum silaturahmi Lembaga dakwah di UPN Veteran Yogyakarta. Kegiatan diisi dengan talkshow, ramah tamah, diskusi terbuka.\n\nTujuan:\n- Menjalin silaturahmi dan kolaborasi antar Lembaga dakwah\n- Menyatukan tujuan\n\nManfaat:\n- Terjalinnya silaturahmi dan kolaborasi antar Lembaga dakwah\n- Tersatukannya tujuan dakwah kampus\n\nSasaran:\n- Seluruh pengurus aktif KMI dan KKMI\n\nTanggal:\n2023-07-30\n\nLokasi:\nMenyesuaikan\n\nParameter Keberhasilan:\n- Terselenggaranya forum dan kolaborasi program",
                'status' => 'aktif',
                'total_biaya' => 0,
                'target_biaya' => 1000000,
            ],
            // ...lanjutkan untuk semua item lain, pastikan hanya field yang sesuai migrasi...
            [
                'nama_kegiatan' => 'Pekan Cinta Nabi',
                'divisi_id' => $divisi[2],
                'deskripsi_kegiatan' => "Gambaran Umum:\nSerangkaian kegiatan yang dimaksudkan untuk memeriahkan hari maulid Nabi Muhammad. Kegiatan-kegiatan yang akan dilaksanakan berupa bedah buku sirah nabawiyah, talkshow, dan podcast.\n\nTujuan:\n- Meningkatkan kecintaan kepada Nabi Muhammad\n- Mengetahui sejarah dan perjuangan Nabi Muhammad\n\nManfaat:\n- Terinspirasi untuk meneladani akhlak Nabi Muhammad\n- Memperoleh pengetahuan tentang sirah nabawiyah\n\nSasaran:\n- Seluruh umat Muslim, khususnya civitas akademika UPN Veteran Yogyakarta\n\nTanggal:\n2023-10-01\n\nLokasi:\nMenyesuaikan\n\nParameter Keberhasilan:\n- Terselenggaranya seluruh rangkaian acara dengan baik",
                'status' => 'aktif',
                'total_biaya' => 0,
                'target_biaya' => 2000000,
            ],
            [
                'nama_kegiatan' => 'Book Review Time',
                'divisi_id' => $divisi[2],
                'deskripsi_kegiatan' => "Gambaran Umum:\nReview Melaksanakan kegiatan bedah buku atau artikel. Kemudian setiap kader membuat resume atau poin-poin penting dari bacaan yang telah dibaca. Lalu hasil resume didiskusikan bersama dalam suatu Forum.\n\nTujuan:\n- Meningkatkan pemahaman dan penguasaan materi bacaan\n- Melatih kemampuan analisis dan sintesis informasi\n\nManfaat:\n- Terbentuknya pola pikir kritis dan analitis\n- Meningkatnya kemampuan berdiskusi dan berargumen\n\nSasaran:\n- Kader KMI dan KKMI serta mahasiswa umum\n\nTanggal:\n2023-010-10\n\nLokasi:\nMenyesuaikan\n\nParameter Keberhasilan:\n- Terselenggaranya kegiatan bedah buku dan diskusi dengan baik",
                'status' => 'aktif',
                'total_biaya' => 0,
                'target_biaya' => 0,
            ],
            [
                'nama_kegiatan' => 'Keilmuan Information Corner',
                'divisi_id' => $divisi[2],
                'deskripsi_kegiatan' => "Gambaran Umum:\nMemposting materi berupa feed instagram, reels instagram, dan membagikan in􏰁ormasi lomba di instagram keilmuan KMI atau instagram KMI UPN Veteran Yogyakarta\n\nTujuan:\n- Meningkatkan pengetahuan dan wawasan kader tentang keilmuan\n- Menginformasikan lomba-lomba yang berkaitan dengan keilmuan\n\nManfaat:\n- Kader termotivasi untuk mengikuti lomba dan meningkatkan kemampuan\n- Terbentuknya komunitas pembelajar di bidang keilmuan\n\nSasaran:\n- Kader KMI dan KKMI serta mahasiswa umum\n\nTanggal:\n2023-05-025\n\nLokasi:\nDaring\n\nParameter Keberhasilan:\n- Tersedianya materi dan informasi lomba secara rutin di media sosial",
                'status' => 'aktif',
                'total_biaya' => 0,
                'target_biaya' => 0,
            ],
            [
                'nama_kegiatan' => 'Bonding Bareng Keilmuan',
                'divisi_id' => $divisi[2],
                'deskripsi_kegiatan' => "Gambaran Umum:\nSilaturahmi keilmuan dilakukan dengan melakukan kunjungan secara luring dengan konsep acara rihlah antara divisi keilmuan KMI dan keilmuan KKMI. Kunjungan membahas mengenai permasalahan yang dihadapi divisi keilmuan di masing-masing KKMI serta mengupdate program kerja yang dilakukan mereka selama satu periode.\n\nTujuan:\n- Terjalinnya silaturahmi dan kerjasama antara divisi keilmuan KMI dan KKMI\n- Tersusunnya program kerja yang terintegrasi\n\nManfaat:\n- Meningkatkan kekompakan dan sinergi antar kader\n- Memperluas jaringan dan wawasan keilmuan\n\nSasaran:\n- Kader divisi keilmuan KMI dan KKMI\n\nTanggal:\n2023-10-05\n\nLokasi:\nMenyesuaikan\n\nParameter Keberhasilan:\n- Terselenggaranya kunjungan dan diskusi dengan baik",
                'status' => 'aktif',
                'total_biaya' => 0,
                'target_biaya' => 500000,
            ],
            //Divisi Syiar
            [
                'nama_kegiatan' => 'Upgrading Internal Syiar',
                'divisi_id' => $divisi[3],
                'deskripsi_kegiatan' => "Gambaran Umum:\nKegiatan dapat berupa pemberian materi kader syiar atau studi banding dengan LDK eksternal kampus. Materi dan ilmu yang didapatkan tersebut dijadikan sebagai suplementasi bagi kader-kader dalam kepengurusan KMI.\n\nTujuan:\n- Meningkatkan kualitas dan kapasitas kader syiar\n- Menjalin hubungan dan kerjasama dengan LDK eksternal\n\nManfaat:\n- Kader memiliki wawasan dan pengetahuan yang lebih luas\n- Terjalin silaturahmi dan kerjasama yang baik antar LDK\n\nSasaran:\n- Kader divisi syiar KMI dan KKMI\n\nTanggal:\n2023-05-27\n\nLokasi:\nMenyesuaikan\n\nParameter Keberhasilan:\n- Terselenggaranya kegiatan upgrading dengan baik",
                'status' => 'aktif',
                'total_biaya' => 0,
                'target_biaya' => 500000,
            ],
            [
                'nama_kegiatan' => 'Kajian Strategis (Isu-Isu)',
                'divisi_id' => $divisi[3],
                'deskripsi_kegiatan' => "Gambaran Umum:\nKegiatan berupa kajian yang membahas isu-isu islami yang berkembang. Berupa kajian diskusi yang menghasilkan konten. Hasil konten berupa artikel/video/poster yang dibukukan menjadi buletin/jadi bahan podcast.\n\nTujuan:\n- Meningkatkan pemahaman dan kepedulian terhadap isu-isu islami\n- Melatih kemampuan analisis dan kritis kader\n\nManfaat:\n- Kader memiliki wawasan yang lebih luas tentang isu-isu terkini\n- Terbentuknya sikap proaktif dan responsif terhadap isu-isu umat\n\nSasaran:\n- Kader KMI dan KKMI serta mahasiswa umum\n\nTanggal:\n2023-06-14\n\nLokasi:\nMenyesuaikan (Offline)\n\nParameter Keberhasilan:\n- Terselenggaranya kajian dan diskusi dengan baik",
                'status' => 'aktif',
                'total_biaya' => 0,
                'target_biaya' => 0,
            ],
            [
                'nama_kegiatan' => 'Syiar Media',
                'divisi_id' => $divisi[3],
                'deskripsi_kegiatan' => "Gambaran Umum:\nKegiatan berupapembuatan konten di sosial media KMI yang menjadi rujukan dalam meningkatkan kapasitas pengetahuan atau informasi keislaman.\n\nTujuan:\n- Meningkatkan kualitas dan kuantitas konten keislaman di media sosial\n- Menyebarluaskan informasi dan pengetahuan keislaman yang benar\n\nManfaat:\n- Masyarakat luas mendapatkan informasi keislaman yang berkualitas\n- Kader terlatih dalam pembuatan konten dan pengelolaan media sosial\n\nSasaran:\n- Kader KMI dan KKMI serta masyarakat umum\n\nTanggal:\n2023-07-17\n\nLokasi:\nMenyesuaikan\n\nParameter Keberhasilan:\n- Tersedianya konten keislaman yang berkualitas di media sosial",
                'status' => 'aktif',
                'total_biaya' => 0,
                'target_biaya' => 0,
            ],
            [
                'nama_kegiatan' => 'Tabligh Akbar Nasional',
                'divisi_id' => $divisi[3],
                'deskripsi_kegiatan' => "Gambaran Umum:\nKegiatan berupa seminar dan PMF yang berkolaborasi dengan KKMI dan LDK eksternal UPN. Kegiatan Productive Muslim festival (PMF) terdiri dari lomba da’i, essay, dan MTQ.\n\nTujuan:\n- Meningkatkan kualitas dakwah kampus\n- Menjalin kerjasama antar lembaga dakwah\n\nManfaat:\n- Terselenggaranya acara dakwah yang berkualitas\n- Terjalinnya silaturahmi dan kerjasama antar lembaga dakwah\n\nSasaran:\n- Seluruh civitas akademika UPN Veteran Yogyakarta dan masyarakat umum\n\nTanggal:\n2023-09-20\n\nLokasi:\nUPN Veteran Yogyakarta\n\nParameter Keberhasilan:\n- Terselenggaranya acara dengan baik dan lancar",
                'status' => 'aktif',
                'total_biaya' => 0,
                'target_biaya' => 3000000,
            ],
            [
                'nama_kegiatan' => 'Kolaborasi dengan KOMPAQ (Pembinaan Al-Qur’an)',
                'divisi_id' => $divisi[3],
                'deskripsi_kegiatan' => "Gambaran Umum:\nKegiatan berupa survey kemampuan mahasiswa dalam membaca Al-Qur’an sebagai data lampiran Proposal Pembinaan. Dari hasil proposal tersebut bisa menyediakan stand di setiap KKMI untuk pembinaan Al-Qur’an. Target Survey selama 1-2 pekan, Tingkatan Level: Mudah (KMI dan KKMI), Lumayan Mudah (Teman dekat), Sulit (Umum).\n\nTujuan:\n- Mengetahui tingkat kemampuan membaca Al-Qur'an di kalangan mahasiswa\n- Menyusun program pembinaan Al-Qur'an yang tepat sasaran\n\nManfaat:\n- Mahasiswa terbantu dalam meningkatkan kemampuan membaca Al-Qur'an\n- Tersusunnya program pembinaan yang terarah dan efektif\n\nSasaran:\n- Seluruh mahasiswa UPN Veteran Yogyakarta\n\nTanggal:\n2023-05-10\n\nLokasi:\nUPN Veteran Yogyakarta\n\nParameter Keberhasilan:\n- Terselenggaranya survey dan pembinaan dengan baik",
                'divisi_id' => $divisi[3],
                'status' => 'aktif',
                'total_biaya' => 0,
                'target_biaya' => 500000,
            ],
            [
                'nama_kegiatan' => 'Kurikulum Syiar untuk KKMI (Kontrol KKMI)',
                'divisi_id' => $divisi[3],
                'deskripsi_kegiatan' => "Gambaran Umum:\nKegiatan merupakan salah satu bentuk kontrol KKMI dengan menyusun kurikulum syiar untuk divisi Syiar KMI dan KKMI UPNVY.\n\nTujuan:\n- Tersusunnya kurikulum syiar yang terstandarisasi untuk KMI dan KKMI\n- Meningkatkan kualitas dakwah dan syiar di kampus\n\nManfaat:\n- Kader memiliki pedoman yang jelas dalam melaksanakan tugas dan fungsi sebagai penggerak syiar\n- Terwujudnya sinergi antara KMI dan KKMI dalam pelaksanaan program kerja\n\nSasaran:\n- Divisi Syiar KMI dan KKMI\n\nTanggal:\n2023-06-27\n\nLokasi:\nKampus 1 dan 2\n\nParameter Keberhasilan:\n- Tersusunnya kurikulum syiar dan diterapkannya dalam program kerja",
                'status' => 'aktif',
                'total_biaya' => 0,
                'target_biaya' => 0,
            ],
            [
                'nama_kegiatan' => 'Database Syiar (Pemetaan Target Dakwah)',
                'divisi_id' => $divisi[3],
                'deskripsi_kegiatan' => "Gambaran Umum:\nKegiatan berupa pengumpulan data, melalui riset dan survei target dakwah kampus.\n\nTujuan:\n- Tersedianya data yang akurat tentang kondisi dan kebutuhan dakwah di kampus\n- Memudahkan dalam penyusunan program kerja yang berbasis data\n\nManfaat:\n- Program kerja yang disusun lebih tepat sasaran dan efektif\n- Tersedianya data untuk evaluasi dan pengembangan program dakwah\n\nSasaran:\n- Seluruh mahasiswa UPN Veteran Yogyakarta\n\nTanggal:\n2023-05-28\n\nLokasi:\nKampus 1 dan 2\n\nParameter Keberhasilan:\n- Terselenggaranya riset dan survei serta tersusunnya laporan hasil riset",
                'status' => 'aktif',
                'total_biaya' => 0,
                'target_biaya' => 0,
            ],
            //Divisi Danus
            [ 
                'nama_kegiatan' => 'Pembuatan Jaket / PDH KMI',
                'divisi_id' => $divisi[4],
                'deskripsi_kegiatan' => "Gambaran Umum:\nPengadaan jaket KMI menggunakan sistem Pre-Order dengan pembayaran melalui cash ataupun transfer.\n\nTujuan:\n- Menjadi identitas KMI\n\nManfaat:\n- Memperkenalkan KMI kepada mahasiswa baru\n\nSasaran:\n- Seluruh anggota KMI\n\nParameter Keberhasilan:\n- Terdistribusinya jaket kepada anggota",
                'status' => 'aktif',
                'total_biaya' => 0,
                'target_biaya' => 2500000,
            ],
            [ 
                'nama_kegiatan' => 'Online Shop',
                'divisi_id' => $divisi[4],
                'deskripsi_kegiatan' => "Gambaran Umum:\nSistem kegiatan pembelian melalui media sosial untuk memperluas pasar dan memudahkan transaksi.\n\nTujuan:\n- Memudahkan konsumen dan penjual dalam transaksi\n- Memperluas pasar dan sasaran\n\nManfaat:\n- Meningkatkan pemasukan dan promosi produk\n\nSasaran:\n- Mahasiswa dan masyarakat umum\n\nParameter Keberhasilan:\n- Terlaksananya transaksi online shop secara rutin",
                'status' => 'aktif',
                'total_biaya' => 0,
                'target_biaya' => 0,
            ],
            [ 
                'nama_kegiatan' => 'Kolaborasi Danus KMI & KKMI',
                'divisi_id' => $divisi[4],
                'deskripsi_kegiatan' => "Gambaran Umum:\nSharing dan pendataan usaha kader KMI/KKMI untuk mengembangkan usaha bersama dan meningkatkan penjualan.\n\nTujuan:\n- Membangun silaturahmi dan kerjasama usaha\n\nManfaat:\n- Meningkatkan pemasukan dan peluang usaha bersama\n\nSasaran:\n- Kader KMI dan KKMI\n\nParameter Keberhasilan:\n- Terlaksananya kolaborasi dan peningkatan penjualan",
                'status' => 'aktif',
                'total_biaya' => 0,
                'target_biaya' => 0,
            ],
            //Divisi Kemuslimahan
            [ 
                'nama_kegiatan' => 'Forum Bersama KKMI',
                'divisi_id' => $divisi[5],
                'deskripsi_kegiatan' => "Gambaran Umum:\nSharing kondisi kemuslimahan di UPNVY dan membahas penjagaan serta sinergi antar lembaga.\n\nTujuan:\n- Menyatukan visi kemuslimahan\n\nManfaat:\n- Meningkatkan sinergi dan kepedulian\n\nSasaran:\n- Pengurus kemuslimahan KMI dan KKMI\n\nParameter Keberhasilan:\n- Terselenggaranya forum dan tercapainya kesepakatan bersama",
                'status' => 'aktif',
                'total_biaya' => 0,
                'target_biaya' => 0,
            ],
            [ 
                'nama_kegiatan' => 'Konten Kemuslimahan',
                'divisi_id' => $divisi[5],
                'deskripsi_kegiatan' => "Gambaran Umum:\nSyiar kemuslimahan melalui konten di media sosial berupa reminder, pengetahuan, isu, challenge, dan informasi.\n\nTujuan:\n- Meningkatkan literasi dan kepedulian muslimah\n\nManfaat:\n- Menambah wawasan dan motivasi\n\nSasaran:\n- Muslimah UPNVY dan masyarakat umum\n\nParameter Keberhasilan:\n- Konten terpublikasi secara rutin",
                'status' => 'aktif',
                'total_biaya' => 0,
                'target_biaya' => 0,
            ],
            [ 
                'nama_kegiatan' => 'Program Tahsin Muslimah',
                'divisi_id' => $divisi[5],
                'deskripsi_kegiatan' => "Gambaran Umum:\nPembelajaran tahsin bekerjasama dengan KOMPAQ untuk meningkatkan kemampuan membaca Al-Qur'an.\n\nTujuan:\n- Meningkatkan kemampuan membaca Al-Qur'an\n\nManfaat:\n- Muslimah lebih fasih membaca Al-Qur'an\n\nSasaran:\n- Muslimah KMI dan KKMI\n\nParameter Keberhasilan:\n- Peserta rutin mengikuti tahsin dan mengalami peningkatan",
                'divisi_id' => $divisi[5],
                'status' => 'aktif',
                'total_biaya' => 0,
                'target_biaya' => 0,
            ],
            [ 
                'nama_kegiatan' => 'Upgrading Kemuslimahan',
                'divisi_id' => $divisi[5],
                'deskripsi_kegiatan' => "Gambaran Umum:\nKajian keislaman, sharing pengetahuan, dan pelatihan softskill untuk kebutuhan muslimah.\n\nTujuan:\n- Meningkatkan kapasitas dan keterampilan muslimah\n\nManfaat:\n- Muslimah lebih percaya diri dan terampil\n\nSasaran:\n- Muslimah KMI dan KKMI\n\nParameter Keberhasilan:\n- Terselenggaranya pelatihan dan kajian secara berkala",
                'status' => 'aktif',
                'total_biaya' => 0,
                'target_biaya' => 300000,
            ],
            //Divisi Media
            [ 
                'nama_kegiatan' => 'Media Service',
                'divisi_id' => $divisi[6],
                'deskripsi_kegiatan' => "Gambaran Umum:\nPelayanan publikasi dan pembuatan poster bagi divisi KMI dan eksternal melalui SOP yang ada.\n\nTujuan:\n- Mendukung kebutuhan publikasi organisasi\n\nManfaat:\n- Memudahkan promosi dan penyebaran informasi\n\nSasaran:\n- Seluruh divisi KMI dan eksternal\n\nParameter Keberhasilan:\n- Permintaan publikasi dan poster terpenuhi tepat waktu",
                'status' => 'aktif',
                'total_biaya' => 0,
                'target_biaya' => 0,
            ],
            [ 
                'nama_kegiatan' => 'Media Content',
                'divisi_id' => $divisi[6],
                'deskripsi_kegiatan' => "Gambaran Umum:\nPembuatan konten kreatif melalui media sosial KMI seperti Instagram, Facebook, Twitter, dan Youtube.\n\nTujuan:\n- Meningkatkan eksistensi dan engagement KMI di media sosial\n\nManfaat:\n- Menarik minat mahasiswa dan masyarakat\n\nSasaran:\n- Mahasiswa UPNVY dan masyarakat umum\n\nParameter Keberhasilan:\n- Konten terpublikasi secara rutin dan menarik",
                'status' => 'aktif',
                'total_biaya' => 0,
                'target_biaya' => 0,
            ],
            [ 
                'nama_kegiatan' => 'Skibu (Skill Booster)',
                'divisi_id' => $divisi[6],
                'deskripsi_kegiatan' => "Gambaran Umum:\nPelatihan pengelolaan sosial media dan pembuatan desain konten untuk meningkatkan skill kader.\n\nTujuan:\n- Meningkatkan kemampuan kader dalam bidang media\n\nManfaat:\n- Kader lebih kreatif dan produktif\n\nSasaran:\n- Kader divisi media KMI dan KKMI\n\nParameter Keberhasilan:\n- Kader mampu membuat konten dan mengelola media sosial",
                'status' => 'aktif',
                'total_biaya' => 0,
                'target_biaya' => 0,
            ],
            [ 
                'nama_kegiatan' => 'SOP MEDIA',
                'divisi_id' => $divisi[6],
                'deskripsi_kegiatan' => "Gambaran Umum:\nTata aturan pembuatan poster, publikasi, dan menjadi media partner di lingkungan KMI.\n\nTujuan:\n- Standarisasi proses publikasi dan media partner\n\nManfaat:\n- Proses publikasi lebih terstruktur\n\nSasaran:\n- Seluruh divisi KMI dan eksternal\n\nParameter Keberhasilan:\n- SOP dijalankan dan dipatuhi seluruh pihak terkait",
                'status' => 'aktif',
                'total_biaya' => 0,
                'target_biaya' => 0,
            ],
            //divisi kaderisasi
            [ 
                'nama_kegiatan' => 'Pelatihan Kepemimpinan Kader',
                'divisi_id' => $divisi[7],
                'deskripsi_kegiatan' => "Gambaran Umum:\nPelatihan untuk meningkatkan jiwa kepemimpinan dan softskill kader KMI.\n\nTujuan:\n- Membentuk kader yang siap memimpin dan bertanggung jawab\n\nManfaat:\n- Kader lebih percaya diri dan mampu mengambil keputusan\n\nSasaran:\n- Kader KMI dan KKMI\n\nParameter Keberhasilan:\n- Peserta aktif dan mampu menerapkan materi pelatihan",
                'status' => 'aktif',
                'total_biaya' => 500000,
                'target_biaya' => 1000000,
            ],
            [ 
                'nama_kegiatan' => 'Mentoring Kaderisasi',
                'divisi_id' => $divisi[7],
                'deskripsi_kegiatan' => "Gambaran Umum:\nProgram mentoring rutin untuk membina dan memantau perkembangan kader baru.\n\nTujuan:\n- Membantu kader baru beradaptasi dan berkembang\n\nManfaat:\n- Kader baru lebih terarah dan termotivasi\n\nSasaran:\n- Kader baru KMI dan KKMI\n\nParameter Keberhasilan:\n- Kader baru aktif mengikuti mentoring dan menunjukkan perkembangan",
                'status' => 'aktif',
                'total_biaya' => 0,
                'target_biaya' => 0,
            ],
            [ 
                'nama_kegiatan' => 'Upgrading Kaderisasi',
                'divisi_id' => $divisi[7],
                'deskripsi_kegiatan' => "Gambaran Umum:\nKegiatan upgrading untuk meningkatkan wawasan, motivasi, dan integritas kader.\n\nTujuan:\n- Meningkatkan kualitas dan loyalitas kader\n\nManfaat:\n- Kader lebih solid dan berwawasan luas\n\nSasaran:\n- Seluruh kader KMI dan KKMI\n\nParameter Keberhasilan:\n- Terselenggaranya upgrading dengan partisipasi aktif",
                'status' => 'aktif',
                'total_biaya' => 300000,
                'target_biaya' => 500000,
            ],
            [ 
                'nama_kegiatan' => 'Evaluasi Kinerja Kader',
                'divisi_id' => $divisi[7],
                'deskripsi_kegiatan' => "Gambaran Umum:\nEvaluasi rutin terhadap kinerja dan kontribusi kader selama periode berjalan.\n\nTujuan:\n- Mengetahui perkembangan dan kendala kader\n\nManfaat:\n- Perbaikan strategi pembinaan kader\n\nSasaran:\n- Seluruh kader KMI dan KKMI\n\nParameter Keberhasilan:\n- Tersusunnya laporan evaluasi dan tindak lanjut",
                'status' => 'aktif',
                'total_biaya' => 0,
                'target_biaya' => 0,
            ],
            //divisi jaringan
            [ 
                'nama_kegiatan' => 'Forum Jaringan Lembaga Dakwah',
                'divisi_id' => $divisi[8],
                'deskripsi_kegiatan' => "Gambaran Umum:\nForum silaturahmi dan diskusi antar lembaga dakwah kampus untuk memperkuat jaringan dan kolaborasi.\n\nTujuan:\n- Memperluas jejaring dan kerjasama antar lembaga\n\nManfaat:\n- Kolaborasi program kerja dan pertukaran informasi\n\nSasaran:\n- Lembaga dakwah kampus se-UPN dan eksternal\n\nParameter Keberhasilan:\n- Terselenggaranya forum dan tercapainya kesepakatan kerjasama",
                'status' => 'aktif',
                'total_biaya' => 200000,
                'target_biaya' => 500000,
            ],
            [ 
                'nama_kegiatan' => 'Sharing Session Jaringan',
                'divisi_id' => $divisi[8],
                'deskripsi_kegiatan' => "Gambaran Umum:\nSesi sharing pengalaman dan best practice antar pengurus jaringan lembaga dakwah.\n\nTujuan:\n- Saling belajar dan memperkuat kapasitas jaringan\n\nManfaat:\n- Pengetahuan dan pengalaman baru untuk pengurus\n\nSasaran:\n- Pengurus jaringan KMI dan lembaga mitra\n\nParameter Keberhasilan:\n- Sharing berjalan interaktif dan bermanfaat",
                'status' => 'aktif',
                'total_biaya' => 0,
                'target_biaya' => 0,
            ],
            [ 
                'nama_kegiatan' => 'Database Jaringan',
                'divisi_id' => $divisi[8],
                'deskripsi_kegiatan' => "Gambaran Umum:\nPenyusunan database kontak dan profil lembaga dakwah mitra untuk memudahkan komunikasi dan kolaborasi.\n\nTujuan:\n- Memiliki data jaringan yang terstruktur\n\nManfaat:\n- Memudahkan koordinasi dan kolaborasi\n\nSasaran:\n- Lembaga mitra dan internal KMI\n\nParameter Keberhasilan:\n- Database tersusun dan terupdate secara berkala",
                'status' => 'aktif',
                'total_biaya' => 0,
                'target_biaya' => 0,
            ],
            [ 
                'nama_kegiatan' => 'Kunjungan Jaringan Eksternal',
                'divisi_id' => $divisi[8],
                'deskripsi_kegiatan' => "Gambaran Umum:\nKunjungan ke lembaga eksternal untuk mempererat hubungan dan menjajaki peluang kerjasama.\n\nTujuan:\n- Menjalin relasi dan memperluas jaringan eksternal\n\nManfaat:\n- Peluang kolaborasi program dan pengembangan organisasi\n\nSasaran:\n- Lembaga eksternal dan pengurus KMI\n\nParameter Keberhasilan:\n- Terselenggaranya kunjungan dan tindak lanjut kerjasama",
                'status' => 'aktif',
                'total_biaya' => 400000,
                'target_biaya' => 750000,
            ],
        ];

        // Gunakan insert massal untuk mempercepat eksekusi
        \App\Models\Kegiatan::insert($kegiatan);
    }
}
