<?php

namespace Database\Seeders;

use App\Models\User;
use Illuminate\Support\Str;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $divisiMapping = [
            'Pengurus Inti' => 1,
            'BK KKMI' => 2,
            'Keilmuan' => 3,
            'Syiar' => 4,
            'Dana Usaha' => 5,
            'Kemuslimahan' => 6,
            'Media' => 7,
        ];

        $users = [
            // Pengurus Inti
            [
                'name' => 'Muhammad Latief Fadhilah',
                'email' => 'latief.inti@example.com',
                'nim' => '134220093',
                'prodi' => 'Agroteknologi',
                'fakultas' => 'FP',
                'angkatan' => 2022,
                'role' => 'ketua',
                'divisi_id' => $divisiMapping['Pengurus Inti'],
                'amanah' => 'Ketua Umum',
                'no_hp' => '6289526402549',
                'gender' => 'L',
            ],
            [
                'name' => 'Ayunda Nur Saufani',
                'email' => 'ayunda.inti@example.com',
                'nim' => '143220149',
                'prodi' => 'Ekonomi Pembangunan',
                'fakultas' => 'FEB',
                'angkatan' => 2022,
                'role' => 'wakil',
                'divisi_id' => $divisiMapping['Pengurus Inti'],
                'amanah' => 'Wakil Ketua Umum',
                'no_hp' => '6285156576271',
                'gender' => 'P',
            ],
            [
                'name' => 'Shinta Nursobah Chairani',
                'email' => 'shinta.inti@example.com',
                'nim' => '123220074',
                'prodi' => 'Informatika',
                'fakultas' => 'FTI',
                'angkatan' => 2022,
                'role' => 'sekretaris',
                'divisi_id' => $divisiMapping['Pengurus Inti'],
                'amanah' => 'Sekretaris Umum',
                'no_hp' => '6285526397492',
                'gender' => 'P',
            ],
            [
                'name' => 'Vasorofa Nur Rahmadanti',
                'email' => 'vasorofa.inti@example.com',
                'nim' => '122220127',
                'prodi' => 'Teknik Industri',
                'fakultas' => 'FTI',
                'angkatan' => 2022,
                'role' => 'bendahara',
                'divisi_id' => $divisiMapping['Pengurus Inti'],
                'amanah' => 'Bendahara Umum',
                'no_hp' => '6285643162781',
                'gender' => 'P',
            ],
            // BK KMMI
            [
                'name' => 'Athila Dzaki Azhar',
                'email' => 'athila.bkkmmi@example.com',
                'email_verified_at' => now(),
                'role' => 'ketua',
                'divisi_id' => 2, // BK KKMI
                'prodi' => 'Teknik Kimia',
                'fakultas' => 'FTI',
                'angkatan' => '2022',
                'amanah' => 'Ketua Divisi',
                'no_hp' => '6281338807313',
                'gender' => 'P',
                'nim' => '121220104',
                'nip' => null,
            ],
            [
                'name' => 'Muhammad Yafi Fathoni',
                'email' => 'yafi.bkkmmi@example.com',
                'email_verified_at' => now(),
                'role' => 'wakil',
                'divisi_id' => 2,
                'prodi' => 'Teknik Pertambangan',
                'fakultas' => 'FTM',
                'angkatan' => '2023',
                'amanah' => 'Wakil Ketua Divisi',
                'no_hp' => '62895397590200',
                'gender' => 'L',
                'nim' => '112230094',
                'nip' => null,
            ],
            [
                'name' => 'Suroya Nazma Huriyah',
                'email' => 'suroya.bkkmmi@example.com',
                'email_verified_at' => now(),
                'role' => 'anggota',
                'divisi_id' => 2,
                'prodi' => 'Teknik Kimia',
                'fakultas' => 'FTI',
                'angkatan' => '2024',
                'amanah' => 'Staff',
                'no_hp' => '6285794929638',
                'gender' => 'P',
                'nim' => '121240132',
                'nip' => null,
            ],
            [
                'name' => 'Annisa Indriani',
                'email' => 'annisa.bkkmmi@example.com',
                'email_verified_at' => now(),
                'role' => 'anggota',
                'divisi_id' => 2,
                'prodi' => 'Akuntansi',
                'fakultas' => 'FEB',
                'angkatan' => '2024',
                'amanah' => 'Staff',
                'no_hp' => '6287736653765',
                'gender' => 'P',
                'nim' => '142240131',
                'nip' => null,
            ],
            [
                'name' => 'Farhan Mufid Muhammad',
                'email' => 'farhan.bkkmmi@example.com',
                'email_verified_at' => now(),
                'role' => 'anggota',
                'divisi_id' => 2,
                'prodi' => 'Hubungan Internasional',
                'fakultas' => 'FISIP',
                'angkatan' => '2023',
                'amanah' => 'Staff',
                'no_hp' => '6285697677470',
                'gender' => 'L',
                'nim' => '151230166',
                'nip' => null,
            ],
            [
                'name' => 'Muhammad Ikhsan Firdaus Saelan',
                'email' => 'ikhsan.bkkmmi@example.com',
                'email_verified_at' => now(),
                'role' => 'anggota',
                'divisi_id' => 2,
                'prodi' => 'Informatika',
                'fakultas' => 'FTI',
                'angkatan' => '2024',
                'amanah' => 'Staff',
                'no_hp' => '6281223548394',
                'gender' => 'L',
                'nim' => '123240202',
                'nip' => null,
            ],
            // Kaderisasi
            [
                'name' => 'Maytha Ayu Rachmawati',
                'email' => 'maytha.keilmuan@example.com',
                'email_verified_at' => now(),
                'role' => 'ketua',
                'divisi_id' => 3, // Kaderisasi
                'prodi' => 'Akuntansi',
                'fakultas' => 'FEB',
                'angkatan' => '2022',
                'amanah' => 'Ketua Divisi',
                'no_hp' => '6285879414833',
                'gender' => 'P',
                'nim' => '142220151',
                'nip' => null,
            ],
            [
                'name' => 'Isnu Angga Winata',
                'email' => 'isnu.keilmuan@example.com',
                'email_verified_at' => now(),
                'role' => 'wakil',
                'divisi_id' => 3,
                'prodi' => 'Akuntansi',
                'fakultas' => 'FEB',
                'angkatan' => '2023',
                'amanah' => 'Wakil Ketua Divisi',
                'no_hp' => '6285641660155',
                'gender' => 'L',
                'nim' => '142230229',
                'nip' => null,
            ],
            [
                'name' => 'Nisrina Taqiyah',
                'email' => 'nisrina.keilmuan@example.com',
                'email_verified_at' => now(),
                'role' => 'wakil',
                'divisi_id' => 3,
                'prodi' => 'Administrasi Bisnis',
                'fakultas' => 'FISIP',
                'angkatan' => '2022',
                'amanah' => 'Wakil Ketua Divisi',
                'no_hp' => '6289676166609',
                'gender' => 'P',
                'nim' => '152220065',
                'nip' => null,
            ],
            [
                'name' => 'Tabriza Aqila',
                'email' => 'tabriza.keilmuan@example.com',
                'email_verified_at' => now(),
                'role' => 'anggota',
                'divisi_id' => 3,
                'prodi' => 'Hubungan Masyarakat',
                'fakultas' => 'FISIP',
                'angkatan' => '2023',
                'amanah' => 'Staff',
                'no_hp' => '62895326932277',
                'gender' => 'P',
                'nim' => '154230022',
                'nip' => null,
            ],
            [
                'name' => 'Renza Juheni',
                'email' => 'renza.keilmuan@example.com',
                'email_verified_at' => now(),
                'role' => 'anggota',
                'divisi_id' => 3,
                'prodi' => 'Manajemen',
                'fakultas' => 'FEB',
                'angkatan' => '2022',
                'amanah' => 'Staff',
                'no_hp' => '6285147043278',
                'gender' => 'L',
                'nim' => '141220235',
                'nip' => null,
            ],
            [
                'name' => 'Ahmad Mu\'tashim Rantisi',
                'email' => 'ahmad.keilmuan@example.com',
                'email_verified_at' => now(),
                'role' => 'anggota',
                'divisi_id' => 3,
                'prodi' => 'Teknik Perminyakan',
                'fakultas' => 'FTM',
                'angkatan' => '2024',
                'amanah' => 'Staff',
                'no_hp' => '6282183844213',
                'gender' => 'L',
                'nim' => '113240045',
                'nip' => null,
            ],
            [
                'name' => 'Alfath Hanif Baihaqi',
                'email' => 'alfath.keilmuan@example.com',
                'email_verified_at' => now(),
                'role' => 'anggota',
                'divisi_id' => 3,
                'prodi' => 'Teknik Perminyakan',
                'fakultas' => 'FTM',
                'angkatan' => '2023',
                'amanah' => 'Staff',
                'no_hp' => '6288218144794',
                'gender' => 'L',
                'nim' => '113230203',
                'nip' => null,
            ],
            [
                'name' => 'Abyaz Affanzaky Shanahan',
                'email' => 'abyaz.keilmuan@example.com',
                'email_verified_at' => now(),
                'role' => 'anggota',
                'divisi_id' => 3,
                'prodi' => 'Informatika',
                'fakultas' => 'FTI',
                'angkatan' => '2024',
                'amanah' => 'Staff',
                'no_hp' => '62895385793113',
                'gender' => 'L',
                'nim' => '123240130',
                'nip' => null,
            ],
            // Syiar
            [
                'name' => 'Haqqil Maulana',
                'email' => 'haqqil.maulana@example.com',
                'email_verified_at' => now(),
                'role' => 'ketua',
                'divisi_id' => 4,
                'prodi' => 'Teknik Perminyakan',
                'fakultas' => 'FTM',
                'angkatan' => 22,
                'amanah' => 'Ketua Divisi',
                'no_hp' => '6282261320563',
                'gender' => 'L',
                'nim' => '113220038',
                'nip' => null,
            ],
            [
                'name' => 'Azza Jauza Zulfa Laudza Muslim',
                'email' => 'azza.jauza@example.com',
                'email_verified_at' => now(),
                'role' => 'anggota',
                'divisi_id' => 4,
                'prodi' => 'Hubungan Masyarakat',
                'fakultas' => 'FISIP',
                'angkatan' => 23,
                'amanah' => 'Wakil Ketua Divisi',
                'no_hp' => '6285156784144',
                'gender' => 'P',
                'nim' => '154230090',
                'nip' => null,
            ],
            [
                'name' => 'Ridho Wahyu Pratama',
                'email' => 'ridho.wahyu@example.com',
                'email_verified_at' => now(),
                'role' => 'anggota',
                'divisi_id' => 4,
                'prodi' => 'Teknik Perminyakan',
                'fakultas' => 'FTM',
                'angkatan' => 23,
                'amanah' => 'Staff',
                'no_hp' => '6289687567744',
                'gender' => 'L',
                'nim' => '113230153',
                'nip' => null,
            ],
            [
                'name' => 'Indah Latifa Kamil',
                'email' => 'indah.latifa@example.com',
                'email_verified_at' => now(),
                'role' => 'anggota',
                'divisi_id' => 4,
                'prodi' => 'Hubungan Internasional',
                'fakultas' => 'FISIP',
                'angkatan' => 23,
                'amanah' => 'Staff',
                'no_hp' => '6282141664671',
                'gender' => 'P',
                'nim' => '151230033',
                'nip' => null,
            ],
            [
                'name' => 'Rina Desi Hartati',
                'email' => 'rina.desi@example.com',
                'email_verified_at' => now(),
                'role' => 'anggota',
                'divisi_id' => 4,
                'prodi' => 'Ekonomi Pembangunan',
                'fakultas' => 'FEB',
                'angkatan' => 24,
                'amanah' => 'Staff',
                'no_hp' => '6285716526637',
                'gender' => 'P',
                'nim' => '143240004',
                'nip' => null,
            ],
            [
                'name' => 'Rohani',
                'email' => 'rohani@example.com',
                'email_verified_at' => now(),
                'role' => 'anggota',
                'divisi_id' => 4,
                'prodi' => 'Teknik Kimia',
                'fakultas' => 'FTI',
                'angkatan' => 24,
                'amanah' => 'Staff',
                'no_hp' => '6282322104770',
                'gender' => 'P',
                'nim' => '121240105',
                'nip' => null,
            ],
            [
                'name' => 'Shafiq Shidqi Azizi',
                'email' => 'shafiq.shidqi@example.com',
                'email_verified_at' => now(),
                'role' => 'anggota',
                'divisi_id' => 4,
                'prodi' => 'Informatika',
                'fakultas' => 'FTI',
                'angkatan' => 24,
                'amanah' => 'Staff',
                'no_hp' => '6285860242402',
                'gender' => 'L',
                'nim' => '123240085',
                'nip' => null,
            ],
            // Dana Usaha
            [
                'name' => 'Aina Uke Nur Aisyah',
                'email' => 'aina.danausaha@example.com',
                'email_verified_at' => now(),
                'role' => 'ketua',
                'divisi_id' => 5,
                'prodi' => 'Administrasi Bisnis',
                'fakultas' => 'FISIP',
                'angkatan' => '2023',
                'amanah' => 'Ketua Divisi',
                'no_hp' => '62895324105735',
                'gender' => 'P',
                'nim' => '152230014',
                'nip' => null,
            ],
            [
                'name' => 'Syifa Agustina Putri Nurhaliza',
                'email' => 'syifa.danausaha@example.com',
                'email_verified_at' => now(),
                'role' => 'wakil',
                'divisi_id' => 5,
                'prodi' => 'Teknik Lingkungan',
                'fakultas' => 'FTM',
                'angkatan' => '2023',
                'amanah' => 'Wakil Ketua Divisi',
                'no_hp' => '6285729967870',
                'gender' => 'P',
                'nim' => '114230023',
                'nip' => null,
            ],
            [
                'name' => 'Amr Habib Santosa',
                'email' => 'amr.danausaha@example.com',
                'email_verified_at' => now(),
                'role' => 'anggota',
                'divisi_id' => 5,
                'prodi' => 'Manajemen',
                'fakultas' => 'FEB',
                'angkatan' => '2024',
                'amanah' => 'Staff',
                'no_hp' => '62895339627889',
                'gender' => 'L',
                'nim' => '141240780',
                'nip' => null,
            ],
            [
                'name' => 'Amelia Rahmawati',
                'email' => 'amelia.danausaha@example.com',
                'email_verified_at' => now(),
                'role' => 'anggota',
                'divisi_id' => 5,
                'prodi' => 'Administrasi Bisnis',
                'fakultas' => 'FISIP',
                'angkatan' => '2024',
                'amanah' => 'Staff',
                'no_hp' => '62895366034864',
                'gender' => 'P',
                'nim' => '152240195',
                'nip' => null,
            ],
            // Kemuslimahan
            [
                'name' => 'Afaf Khairunnisa Fadhilah',
                'email' => 'afaf.kemuslimahan@example.com',
                'email_verified_at' => now(),
                'role' => 'ketua',
                'divisi_id' => 6,
                'prodi' => 'Hubungan Masyarakat',
                'fakultas' => 'FISIP',
                'angkatan' => '2022',
                'amanah' => 'Ketua Divisi',
                'no_hp' => '6289674079944',
                'gender' => 'P',
                'nim' => '154220058',
                'nip' => null,
            ],
            [
                'name' => 'Hanifah Rahmani Pramestuti',
                'email' => 'hanifah.kemuslimahan@example.com',
                'email_verified_at' => now(),
                'role' => 'wakil',
                'divisi_id' => 6,
                'prodi' => 'Teknik Lingkungan',
                'fakultas' => 'FTM',
                'angkatan' => '2022',
                'amanah' => 'Wakil Ketua Divisi',
                'no_hp' => '6285800648688',
                'gender' => 'P',
                'nim' => '114220033',
                'nip' => null,
            ],
            [
                'name' => 'Alfika Noor Rachmadani',
                'email' => 'alfika.kemuslimahan@example.com',
                'email_verified_at' => now(),
                'role' => 'anggota',
                'divisi_id' => 6,
                'prodi' => 'Manajemen',
                'fakultas' => 'FEB',
                'angkatan' => '2022',
                'amanah' => 'Staff',
                'no_hp' => '6885740224408',
                'gender' => 'P',
                'nim' => '141220104',
                'nip' => null,
            ],
            [
                'name' => 'Karima Alhusna',
                'email' => 'karima.kemuslimahan@example.com',
                'email_verified_at' => now(),
                'role' => 'anggota',
                'divisi_id' => 6,
                'prodi' => 'Teknik Kimia',
                'fakultas' => 'FTI',
                'angkatan' => '2024',
                'amanah' => 'Staff',
                'no_hp' => '6282115926415',
                'gender' => 'P',
                'nim' => '121240199',
                'nip' => null,
            ],
            [
                'name' => 'Salju Rayu Raya Ristyrouva',
                'email' => 'salju.kemuslimahan@example.com',
                'email_verified_at' => now(),
                'role' => 'anggota',
                'divisi_id' => 6,
                'prodi' => 'D3 Teknik Kimia',
                'fakultas' => 'FTI',
                'angkatan' => '2024',
                'amanah' => 'Staff',
                'no_hp' => '6281225149494',
                'gender' => 'P',
                'nim' => '021240026',
                'nip' => null,
            ],
            // Media
            [
                'name' => 'Aisha Hauna Amatullah',
                'email' => 'aisha.media@example.com',
                'email_verified_at' => now(),
                'role' => 'ketua',
                'divisi_id' => 7,
                'prodi' => 'Komunikasi',
                'fakultas' => 'FISIP',
                'angkatan' => '2022',
                'amanah' => 'Ketua Divisi',
                'no_hp' => '628112250096',
                'gender' => 'P',
                'nim' => '153220040',
                'nip' => null,
            ],
            [
                'name' => 'Faiz Muhammad Al Ghifari',
                'email' => 'faiz.media@example.com',
                'email_verified_at' => now(),
                'role' => 'wakil',
                'divisi_id' => 7,
                'prodi' => 'Informatika',
                'fakultas' => 'FTI',
                'angkatan' => '2023',
                'amanah' => 'Wakil Ketua Divisi',
                'no_hp' => '6281327019714',
                'gender' => 'L',
                'nim' => '123230128',
                'nip' => null,
            ],
            [
                'name' => 'Balangga Muhammad',
                'email' => 'balangga.media@example.com',
                'email_verified_at' => now(),
                'role' => 'anggota',
                'divisi_id' => 7,
                'prodi' => 'Agribisnis',
                'fakultas' => 'FP',
                'angkatan' => '2022',
                'amanah' => 'Staff',
                'no_hp' => '6285866311354',
                'gender' => 'L',
                'nim' => '135220045',
                'nip' => null,
            ],
            [
                'name' => 'Laviotis Thoriq Pradana',
                'email' => 'laviotis.media@example.com',
                'email_verified_at' => now(),
                'role' => 'anggota',
                'divisi_id' => 7,
                'prodi' => 'Ekonomi Pembangunan',
                'fakultas' => 'FEB',
                'angkatan' => '2024',
                'amanah' => 'Staff',
                'no_hp' => '628882567400',
                'gender' => 'L',
                'nim' => '143240149',
                'nip' => null,
            ],
            [
                'name' => 'Rahmat Saktiawan',
                'email' => 'rahmat.media@example.com',
                'email_verified_at' => now(),
                'role' => 'anggota',
                'divisi_id' => 7,
                'prodi' => 'Teknik Perminyakan',
                'fakultas' => 'FTM',
                'angkatan' => '2023',
                'amanah' => 'Staff',
                'no_hp' => '6281274494838',
                'gender' => 'L',
                'nim' => '113230030',
                'nip' => null,
            ],
            [
                'name' => 'Falzhafia Najmii Aisyah Archman',
                'email' => 'falzhafia.media@example.com',
                'email_verified_at' => now(),
                'role' => 'anggota',
                'divisi_id' => 7,
                'prodi' => 'Akuntansi',
                'fakultas' => 'FEB',
                'angkatan' => '2023',
                'amanah' => 'Staff',
                'no_hp' => '6287761701659',
                'gender' => 'P',
                'nim' => '142230347',
                'nip' => null,
            ],
        ];

        // Add default password and timestamps to all users
        $timestamp = now();
        $defaultPassword = Hash::make('password');

        foreach ($users as &$data) {
            $data['password'] = $defaultPassword; // Use precomputed password
            $data['email_verified_at'] = $data['email_verified_at'] ?? null;
            $data['nip'] = $data['nip'] ?? null;
            $data['created_at'] = $timestamp;
            $data['updated_at'] = $timestamp;
        }

        // Batch insert users for better performance
        $batchSize = 500; // Adjust batch size as needed
        foreach (array_chunk($users, $batchSize) as $batch) {
            User::insert($batch);
        }
    }
}
